### ISSUE TITLE
New NPM package?

### ISSUE THREAD

**Issue by gtamas** [InfoSec812/npm-audit-ci-wrapper#48]
The current NPM package does not support Windows at all. I can see this is fixed in master, it would be great to publish this to NPM. When can we expect a new version to be published?

Thanks in advance!

**Comment by InfoSec812** [comment]
Hmmm... Travis SHOULD have published it automatically... I will try to take a look today.

**Comment by gtamas** [comment]
Thx!

**Comment by InfoSec812** [comment]
For some reason TravisCI is not able to publish even after I double checked the API Token, so I have published 2.4.3 manually to NPMjs.org
