### ISSUE TITLE
Add whitelist - feature request

### ISSUE THREAD

**Issue by d0tkom** [InfoSec812/npm-audit-ci-wrapper#5]
Hi,

It would be very useful for specific cases when you can't update a package, to just be able to whitelist that given package. I already have a crude implementation for this, if you'd consider including it.

**Comment by InfoSec812** [comment]
Submit it as a PR and I would be happy to take a look.

**Comment by InfoSec812** [comment]
@d0tkom I have implemented this feature as requested. Please give it a try and let me know if it works for you. It has not been merged/released yet, so here's how to install it:

```
npm uninstall -g npm-audit-ci-wrapper
npm install -g git+https://github.com/InfoSec812/npm-audit-ci-wrapper.git#Issue-5_-_Add_whitelist_feature
```

Once I get your review/evaluation I will work on getting it merged and released to NPM.

Cheers!

**Comment by d0tkom** [comment]
Thanks a lot for implementing this!

**Comment by InfoSec812** [comment]
My pleasure! I hope it meets your needs!
