### ISSUE TITLE
Consider using minimist instead of argv for command line parsing

### ISSUE THREAD

**Issue by helio-frota** [InfoSec812/npm-audit-ci-wrapper#71]
Main reasons:

1)  the size of the module
2)  minimist is still being maintained.

https://www.npmjs.com/package/minimist
https://github.com/substack/minimist

argv in other hand looks abandoned since 2014
https://github.com/codenothing/argv

**Comment by InfoSec812** [comment]
I highly recommend that you use Sonatype's auditjs as a replacement. I am just going to mark this project as deprecated.
