### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by drc-tjuszczyk** [InfoSec812/npm-audit-ci-wrapper#8]
Does this work on windows right now?

**Comment by InfoSec812** [comment]
I do not have a Windows Computer to test with, but IIRC some of my clients used it successfully on Windows.

**Comment by InfoSec812** [comment]
@drc-tjuszczyk Did you ever check to see if this is working on Windows? I'd like to know so I can close this out.

**Comment by tommybananas** [comment]
I never ended up trying it so I'll close for now
